"""add models

Revision ID: 23e34ef21e22
Revises: 22b5877369d3
Create Date: 2024-07-20 15:38:16.071278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e34ef21e22'
down_revision = '22b5877369d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_shortage_notification_receivers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('water_shortage_notification_id', sa.Integer(), nullable=True),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.Column('has_seen', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['responsible_id'], ['responsible.id_responsible'], ),
    sa.ForeignKeyConstraint(['water_shortage_notification_id'], ['water_shortage_notification.id_notification'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waste_notification_receivers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('waste_notification_id', sa.Integer(), nullable=True),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.Column('has_seen', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['responsible_id'], ['responsible.id_responsible'], ),
    sa.ForeignKeyConstraint(['waste_notification_id'], ['waste_notification.id_notification'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waste_notification_receivers')
    op.drop_table('water_shortage_notification_receivers')
    # ### end Alembic commands ###
