"""Initial migration

Revision ID: 371e86456070
Revises: 1eed30d6f655
Create Date: 2024-07-20 07:09:26.721138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371e86456070'
down_revision = '1eed30d6f655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id_subscription', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('validity', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_subscription')
    )
    op.create_table('super_admin',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('super_admin')
    op.drop_table('subscription')
    # ### end Alembic commands ###
