"""Updated SuperAdmin model with correct id_user handling

Revision ID: 75e5e1de502d
Revises: ae2c6d4ea406
Create Date: 2024-07-20 09:29:03.615702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75e5e1de502d'
down_revision = 'ae2c6d4ea406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validity_in_month', sa.Integer(), nullable=False))
        batch_op.drop_column('validity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validity', mysql.DATETIME(), nullable=False))
        batch_op.drop_column('validity_in_month')

    # ### end Alembic commands ###
