"""add responsible model migration

Revision ID: 767c39e48d9c
Revises: 371e86456070
Create Date: 2024-07-20 07:11:10.037212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767c39e48d9c'
down_revision = '371e86456070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responsible',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_subscription', sa.Integer(), nullable=True),
    sa.Column('is_activated', sa.Boolean(), nullable=True),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('activity_domain', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_subscription', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_subscription'], ['subscription.id_subscription'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responsible')
    # ### end Alembic commands ###
