"""Updated SuperAdmin model with correct id_user handling

Revision ID: ae2c6d4ea406
Revises: 
Create Date: 2024-07-20 08:26:30.711581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae2c6d4ea406'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('super_admin',
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('profile', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id_superadmin', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_superadmin'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('responsible',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_subscription', sa.Integer(), nullable=True),
    sa.Column('is_activated', sa.Boolean(), nullable=True),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('activity_domain', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_subscription', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_subscription'], ['subscription.id_subscription'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responsible')
    op.drop_table('super_admin')
    # ### end Alembic commands ###
