"""add models

Revision ID: b28d1022ae15
Revises: b764215cd6c8
Create Date: 2024-07-20 10:19:29.736844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b28d1022ae15'
down_revision = 'b764215cd6c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_shortage_notification',
    sa.Column('id_notification', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id_responsible', sa.Integer(), nullable=True),
    sa.Column('id_water_shortage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_responsible'], ['responsible.id_user'], ),
    sa.ForeignKeyConstraint(['id_water_shortage'], ['water_shortage.id_water_shortage'], ),
    sa.PrimaryKeyConstraint('id_notification')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('water_shortage_notification')
    # ### end Alembic commands ###
