"""add models

Revision ID: b764215cd6c8
Revises: d62e9cc763e9
Create Date: 2024-07-20 10:18:54.223261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b764215cd6c8'
down_revision = 'd62e9cc763e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waste_notification',
    sa.Column('id_notification', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id_responsible', sa.Integer(), nullable=True),
    sa.Column('id_waste', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_responsible'], ['responsible.id_user'], ),
    sa.ForeignKeyConstraint(['id_waste'], ['waste.id_waste'], ),
    sa.PrimaryKeyConstraint('id_notification')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waste_notification')
    # ### end Alembic commands ###
