"""add models

Revision ID: d62e9cc763e9
Revises: 75e5e1de502d
Create Date: 2024-07-20 10:15:08.072770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62e9cc763e9'
down_revision = '75e5e1de502d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_shortage',
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id_water_shortage', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flow_rate', sa.Float(), nullable=True),
    sa.Column('quality', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('last_alert', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_water_shortage')
    )
    op.create_table('waste',
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id_waste', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_waste', sa.String(length=255), nullable=True),
    sa.Column('is_checked', sa.Boolean(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_waste')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waste')
    op.drop_table('water_shortage')
    # ### end Alembic commands ###
